# Generated by Django 4.1.7 on 2023-02-16 13:45

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('alternate_name', models.CharField(max_length=128)),
                ('description', models.TextField(max_length=500)),
                ('photo', models.ImageField(upload_to='')),
                ('telephone', models.CharField(max_length=50)),
                ('opening_hours', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('map', models.ImageField(upload_to='')),
                ('maximum_attendee_capacity', models.IntegerField()),
                ('amenity_feature', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('1', 'lift'), ('2', 'parking deck')], max_length=3), size=None)),
            ],
        ),
    ]
