# Generated by Django 4.1.7 on 2023-02-16 13:57

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='geo',
            field=location_field.models.plain.PlainLocationField(default=None, max_length=63),
        ),
    ]
