# Generated by Django 4.1.7 on 2023-02-16 16:50

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_building_geo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('alternate_name', models.CharField(max_length=128)),
                ('description', models.TextField(max_length=500)),
                ('photo', models.ImageField(upload_to='')),
                ('room_location', models.ImageField(upload_to='')),
                ('room_type', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('1', 'CoWorking'), ('2', 'Meeting')], max_length=3), size=None)),
                ('maintenance_availebility', models.BooleanField(default=True)),
                ('maintenance_status', models.TextField(max_length=250)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='api.building')),
            ],
        ),
    ]
