# Generated by Django 4.1.7 on 2023-03-10 19:47

import location_field.models.plain
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_user_managers_remove_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="geo",
            field=location_field.models.plain.PlainLocationField(
                blank=True, default=None, max_length=63, null=True
            ),
        ),
    ]
