# Generated by Django 4.1.7 on 2023-03-20 11:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_building_geo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="building",
            old_name="amenity_feature",
            new_name="amenity_features",
        ),
        migrations.RemoveField(
            model_name="workplace",
            name="favorite_workplace",
        ),
        migrations.AddField(
            model_name="user",
            name="favorite_workplace",
            field=models.ManyToManyField(to="api.workplace"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="email_others",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.EmailField(max_length=254), size=None
            ),
        ),
    ]
