# Generated by Django 4.1.7 on 2023-02-16 16:56

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workplace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('in_room_id', models.IntegerField()),
                ('equipment', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('1', 'Phone'), ('2', 'Dual Screen'), ('3', 'Fax'), ('4', 'USB-C Docking-station'), ('2', 'electric adjustable desk')], max_length=3), size=None)),
                ('maintenance_availebility', models.BooleanField(default=True)),
                ('maintenance_status', models.TextField(max_length=250)),
                ('notification', models.TextField(max_length=500)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workplaces', to='api.room')),
            ],
        ),
    ]
