# Generated by Django 4.1.7 on 2023-03-20 11:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "api",
            "0004_rename_amenity_feature_building_amenity_features_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="favorite_workplace",
            new_name="favorite_workplaces",
        ),
    ]
