# Generated by Django 4.1.7 on 2023-04-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_rename_favorite_workplace_user_favorite_workplaces"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="favorite_workplaces",
            field=models.ManyToManyField(blank=True, to="api.workplace"),
        ),
    ]
