# Generated by Django 4.1.7 on 2023-02-16 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_workplace_favorite_workplace'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='workplace',
            new_name='workplaces',
        ),
    ]
